### ISSUE TITLE
Colors of other authors are not shown

### ISSUE THREAD

**Issue by mitar** [WinMinTun/quill-authorship#2]
And it seems there is no way to register colors for other ids myself. `addAuthor` only works for one author, current author?

**Comment by WinMinTun** [comment]
@mitar I m terribly sorry for missing your issue. Hope my reply helps other ppl with the same issue. The colouring for other authors can be added from styling. My case is that when a user open a doc, the is only one coloring for current user if any. But when another author opens the same doc, I broadcast the user id through websocket and add styling dynamically for that author. Or if you don't use websocket, you can store the author ids of the doc in your db and then add styling dynamically. You can see each authorship is marked by class 'ql-author-userid'.
